name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Common setup
        run: bash scripts/common-setup.sh

      - name: Run prettier
        run: npm run format-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Common setup
        run: bash scripts/common-setup.sh

      - name: Run eslint
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Common setup
        run: bash scripts/common-setup.sh

      - name: Run TypeScript check
        run: npm run typecheck
