name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        run: npm run format-check

      - name: Run eslint
        run: npm run lint

      - name: Run TypeScript check
        run: npm run typecheck

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Build affected applications
        run: |
          npx nx affected:build --base=origin/master~1 --head=origin/HEAD

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Deploy affected applications
        run: |
          npx nx affected --target=deploy --base=origin/master~1 --head=origin/HEAD
